#!/bin/bash

# Sync Zen Browser theme with current Hyprland theme.
# Creates userChrome.css in the active Zen profile's chrome/ directory.
# zen-themes.css (ZenMods) is never touched.

HYPRLAND_CONF="$HOME/.config/hypr/hyprland.conf"
ZEN_DIR="$HOME/.config/zen"
PROFILES_INI="$ZEN_DIR/profiles.ini"

# ── Locate the active profile ──────────────────────────────────────────────
# Use the [Install…] Default line — it's the profile bound to the Zen binary.
ZEN_PROFILE=$(grep -A5 '^\[Install' "$PROFILES_INI" | grep '^Default=' | sed 's/Default=//' | head -1)

if [ -z "$ZEN_PROFILE" ]; then
    # Fallback: first profile marked Default=1
    ZEN_PROFILE=$(awk '/^\[Profile/{prof=$0} /^Default=1/{print prof}' "$PROFILES_INI" \
        | grep -oP '(?<=\[Profile)\d+' | head -1)
    ZEN_PROFILE=$(awk -F= "/^\[Profile$ZEN_PROFILE\]/{f=1} f && /^Path=/{print \$2; exit}" "$PROFILES_INI")
fi

if [ -z "$ZEN_PROFILE" ]; then
    echo "Error: Could not locate active Zen profile in $PROFILES_INI"
    exit 1
fi

ZEN_PROFILE_PATH="$ZEN_DIR/$ZEN_PROFILE"
CHROME_DIR="$ZEN_PROFILE_PATH/chrome"
USER_CHROME="$CHROME_DIR/userChrome.css"
PREFS_JS="$ZEN_PROFILE_PATH/prefs.js"

# ── Get current theme file from Hyprland config ────────────────────────────
THEME_FILE=$(grep "^source.*themes.*\.conf" "$HYPRLAND_CONF" | sed 's/.*= *//')

if [ -z "$THEME_FILE" ] || [ ! -f "$THEME_FILE" ]; then
    echo "Error: Could not determine theme file from Hyprland config"
    exit 1
fi

theme_name=$(basename "$THEME_FILE" .conf)

# Extract a color variable from the theme file
get_color() {
    grep "^\$${1} = rgb(" "$THEME_FILE" | sed -E 's/.*= *rgb\(([^)]+)\).*/\1/' | head -1
}

bg_base=$(get_color 'bg-base')
bg_mantle=$(get_color 'bg-mantle')
fg_primary=$(get_color 'fg-primary')
fg_secondary=$(get_color 'fg-secondary')
accent_blue=$(get_color 'accent-blue')
accent_green=$(get_color 'accent-green')
accent_red=$(get_color 'accent-red')
accent_yellow=$(get_color 'accent-yellow')
surface_0=$(get_color 'surface-0')
surface_1=$(get_color 'surface-1')
border_0=$(get_color 'border-0')

echo "Syncing Zen Browser theme for: $theme_name (profile: $ZEN_PROFILE)"

mkdir -p "$CHROME_DIR"

# ── Write userChrome.css ───────────────────────────────────────────────────
# zen-themes.css is owned by ZenMods — this file is separate and additive.
cat > "$USER_CHROME" << EOF
/* Zen Browser — userChrome.css */
/* Theme: $theme_name — auto-generated by sync-zen-theme.sh */
/* Do not edit by hand; changes will be overwritten on next theme switch.  */
/* zen-themes.css (ZenMods) is untouched.                                  */

/* ── Design tokens ────────────────────────────────────────────────────── */
:root {
    --qs-bg-base:      #$bg_base;
    --qs-bg-mantle:    #$bg_mantle;
    --qs-surface-0:    #$surface_0;
    --qs-surface-1:    #$surface_1;
    --qs-fg-primary:   #$fg_primary;
    --qs-fg-secondary: #$fg_secondary;
    --qs-accent:       #$accent_blue;
    --qs-accent-green: #$accent_green;
    --qs-accent-red:   #$accent_red;
    --qs-accent-yellow:#$accent_yellow;
    --qs-border:       #${border_0}60;
}

/* ── Main toolbar & navigation bar ───────────────────────────────────── */
#navigator-toolbox,
#nav-bar,
#TabsToolbar,
#PersonalToolbar,
toolbar {
    background-color: var(--qs-bg-base) !important;
    background-image: none !important;
    border: none !important;
    box-shadow: none !important;
    color: var(--qs-fg-primary) !important;
}

/* ── Zen sidebar ──────────────────────────────────────────────────────── */
#zen-sidebar-top-buttons-separator,
#zen-appcontent-navbar,
zen-sidebar,
#zenSidebarWrapper,
#zenSidebarContainer,
#zen-sidebar-wrapper {
    background-color: var(--qs-bg-mantle) !important;
    border-color: var(--qs-border) !important;
}

/* Zen workspace / pinned tab icons strip */
#zen-tabbox-wrapper,
#tabbrowser-tabbox {
    background-color: var(--qs-bg-base) !important;
}

/* ── Tabs ─────────────────────────────────────────────────────────────── */
.tabbrowser-tab > .tab-stack > .tab-background {
    background-color: var(--qs-surface-0) !important;
    border: none !important;
    border-radius: 6px !important;
    box-shadow: none !important;
}

.tabbrowser-tab[selected="true"] > .tab-stack > .tab-background {
    background-color: var(--qs-surface-1) !important;
}

.tabbrowser-tab:hover:not([selected="true"]) > .tab-stack > .tab-background {
    background-color: var(--qs-surface-0) !important;
    opacity: 0.8;
}

.tab-label {
    color: var(--qs-fg-secondary) !important;
}

.tabbrowser-tab[selected="true"] .tab-label {
    color: var(--qs-fg-primary) !important;
}

/* Active tab indicator line */
.tab-line {
    background-color: var(--qs-accent) !important;
}

/* ── URL bar ──────────────────────────────────────────────────────────── */
#urlbar,
#urlbar-background,
#urlbar-input-container {
    background-color: var(--qs-surface-1) !important;
    color: var(--qs-fg-primary) !important;
    border: 1px solid var(--qs-border) !important;
    box-shadow: none !important;
    border-radius: 8px !important;
}

#urlbar[focused="true"] #urlbar-background,
#urlbar[open] #urlbar-background {
    border-color: var(--qs-accent) !important;
    box-shadow: 0 0 0 1px var(--qs-accent) !important;
}

#urlbar-input,
#urlbar input {
    color: var(--qs-fg-primary) !important;
}

/* URL bar autocomplete dropdown */
.urlbarView,
#urlbar-results {
    background-color: var(--qs-surface-0) !important;
    border-color: var(--qs-border) !important;
    border-radius: 8px !important;
}

.urlbarView-row {
    color: var(--qs-fg-primary) !important;
}

.urlbarView-row[selected],
.urlbarView-row:hover {
    background-color: var(--qs-accent) !important;
    color: var(--qs-bg-base) !important;
    border-radius: 6px !important;
}

/* ── Toolbar buttons ──────────────────────────────────────────────────── */
toolbarbutton,
.toolbarbutton-1 {
    fill: var(--qs-fg-primary) !important;
    color: var(--qs-fg-primary) !important;
}

toolbarbutton:hover,
.toolbarbutton-1:hover {
    background-color: var(--qs-surface-0) !important;
    border-radius: 6px !important;
}

/* ── Sidebar panel (bookmarks, history, etc.) ─────────────────────────── */
#sidebar-box,
#sidebar-header,
#sidebar {
    background-color: var(--qs-bg-mantle) !important;
    color: var(--qs-fg-primary) !important;
    border-color: var(--qs-border) !important;
}

/* ── Context menus ────────────────────────────────────────────────────── */
menupopup,
menuitem,
menu {
    background-color: var(--qs-surface-1) !important;
    color: var(--qs-fg-primary) !important;
    -moz-appearance: none !important;
    border-color: var(--qs-border) !important;
}

menuitem:hover,
menu[_moz-menuactive="true"],
menuitem[_moz-menuactive="true"] {
    background-color: var(--qs-accent) !important;
    color: var(--qs-bg-base) !important;
}

/* ── Panel popups (extensions, etc.) ─────────────────────────────────── */
.panel-arrowcontent,
.panel-outer-box,
.panel-arrowbox {
    background-color: var(--qs-surface-1) !important;
    border-color: var(--qs-border) !important;
    border-radius: 8px !important;
    box-shadow: 0 4px 16px #${bg_crust:-$bg_base}80 !important;
}

/* ── Bookmarks bar ────────────────────────────────────────────────────── */
#PlacesToolbarItems > .bookmark-item {
    color: var(--qs-fg-primary) !important;
    border-radius: 4px !important;
}

#PlacesToolbarItems > .bookmark-item:hover {
    background-color: var(--qs-surface-0) !important;
}

/* ── Find bar ─────────────────────────────────────────────────────────── */
findbar {
    background-color: var(--qs-surface-0) !important;
    border-top: 1px solid var(--qs-border) !important;
    color: var(--qs-fg-primary) !important;
}

.findbar-textbox {
    background-color: var(--qs-surface-1) !important;
    color: var(--qs-fg-primary) !important;
    border-color: var(--qs-border) !important;
    border-radius: 4px !important;
}

/* ── Notification / info bars ─────────────────────────────────────────── */
notification,
.notificationbox-stack {
    background-color: var(--qs-surface-1) !important;
    color: var(--qs-fg-primary) !important;
    border-bottom: 1px solid var(--qs-border) !important;
}
EOF

# ── Ensure userChrome.css is enabled in Zen ───────────────────────────────
# We only touch prefs.js when Zen is not running to avoid data loss.
PREF_KEY='toolkit.legacyUserProfileCustomizations.stylesheets'
if [ -f "$PREFS_JS" ]; then
    if ! grep -q "$PREF_KEY" "$PREFS_JS"; then
        if pgrep -x zen-browser > /dev/null || pgrep -x zen > /dev/null; then
            echo "Warning: Zen is running — cannot safely write prefs.js."
            echo "  Open about:config, set '$PREF_KEY' to true, then restart Zen."
        else
            echo "user_pref(\"$PREF_KEY\", true);" >> "$PREFS_JS"
            echo "Enabled userChrome.css support in prefs.js"
        fi
    fi
fi

echo "Zen Browser theme synced successfully ($theme_name → $USER_CHROME)"
echo "Restart Zen Browser to apply the new theme."
