#!/bin/bash

# Sync btop theme with current Hyprland theme
# Uses a fixed theme file "theme.theme" so btop.conf's color_theme never needs
# to change (avoids conflicts with btop's save_config_on_exit = true).

HYPRLAND_CONF="$HOME/.config/hypr/hyprland.conf"
BTOP_THEMES_DIR="$HOME/.config/btop/themes"
BTOP_CONF="$HOME/.config/btop/btop.conf"
THEME_FILE_OUT="$BTOP_THEMES_DIR/theme.theme"

# Get current theme file from Hyprland config
THEME_FILE=$(grep "^source.*themes.*\.conf" "$HYPRLAND_CONF" | sed 's/.*= *//')

if [ -z "$THEME_FILE" ] || [ ! -f "$THEME_FILE" ]; then
    echo "Error: Could not determine theme file from Hyprland config"
    exit 1
fi

theme_name=$(basename "$THEME_FILE" .conf)

# Extract a color variable from the theme file
get_color() {
    grep "^\$${1} = rgb(" "$THEME_FILE" | sed -E 's/.*= *rgb\(([^)]+)\).*/\1/' | head -1
}

bg_base=$(get_color 'bg-base')
bg_mantle=$(get_color 'bg-mantle')
fg_primary=$(get_color 'fg-primary')
fg_secondary=$(get_color 'fg-secondary')
accent_blue=$(get_color 'accent-blue')
accent_cyan=$(get_color 'accent-cyan')
accent_green=$(get_color 'accent-green')
accent_yellow=$(get_color 'accent-yellow')
accent_orange=$(get_color 'accent-orange')
accent_red=$(get_color 'accent-red')
accent_purple=$(get_color 'accent-purple')
accent_teal=$(get_color 'accent-teal')
surface_0=$(get_color 'surface-0')
surface_1=$(get_color 'surface-1')
border_0=$(get_color 'border-0')

echo "Syncing btop theme for: $theme_name"

mkdir -p "$BTOP_THEMES_DIR"

cat > "$THEME_FILE_OUT" << EOF
# btop theme: $theme_name
# Auto-generated by sync-btop-theme.sh — do not edit by hand

# Main background (empty = terminal default for transparency)
theme[main_bg]="#$bg_base"

# Main text color
theme[main_fg]="#$fg_primary"

# Title color for boxes
theme[title]="#$accent_blue"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#$accent_yellow"

# Background color of selected item in processes box
theme[selected_bg]="#$surface_1"

# Foreground color of selected item in processes box
theme[selected_fg]="#$fg_primary"

# Color of inactive/disabled text
theme[inactive_fg]="#$border_0"

# Misc colors for processes box (mini cpu graphs, details memory graph)
theme[proc_misc]="#$accent_cyan"

# Box outline colors
theme[cpu_box]="#$border_0"
theme[mem_box]="#$border_0"
theme[net_box]="#$border_0"
theme[proc_box]="#$border_0"

# Box divider line and small boxes line color
theme[div_line]="#$surface_0"

# Temperature graph colors
theme[temp_start]="#$accent_green"
theme[temp_mid]="#$accent_yellow"
theme[temp_end]="#$accent_red"

# CPU graph colors
theme[cpu_start]="#$accent_blue"
theme[cpu_mid]="#$accent_cyan"
theme[cpu_end]="#$fg_primary"

# Mem/Disk free meter
theme[free_start]="#$accent_green"
theme[free_mid]="#$accent_teal"
theme[free_end]="#$accent_cyan"

# Mem/Disk cached meter
theme[cached_start]="#$accent_blue"
theme[cached_mid]="#$accent_purple"
theme[cached_end]="#$accent_purple"

# Mem/Disk available meter
theme[available_start]="#$accent_green"
theme[available_mid]="#$accent_cyan"
theme[available_end]="#$accent_blue"

# Mem/Disk used meter
theme[used_start]="#$accent_green"
theme[used_mid]="#$accent_yellow"
theme[used_end]="#$accent_red"

# Download graph colors
theme[download_start]="#$accent_green"
theme[download_mid]="#$accent_cyan"
theme[download_end]="#$accent_blue"

# Upload graph colors
theme[upload_start]="#$accent_blue"
theme[upload_mid]="#$accent_purple"
theme[upload_end]="#$accent_orange"
EOF

# Ensure btop.conf points to the fixed "theme" filename.
# We only update the line if it's not already set to "theme", so btop's
# save_config_on_exit won't fight us on subsequent runs.
if [ -f "$BTOP_CONF" ]; then
    if ! grep -q '^color_theme = "theme"' "$BTOP_CONF"; then
        sed -i 's|^color_theme = .*|color_theme = "theme"|' "$BTOP_CONF"
        echo "btop.conf: color_theme set to \"theme\""
    fi
else
    echo "Warning: btop.conf not found at $BTOP_CONF"
fi

echo "btop theme synced successfully ($theme_name → $THEME_FILE_OUT)"
