#!/bin/bash

# Sync YouTube Music Desktop App theme with current Hyprland theme.
# Generates a custom CSS file and enables it via the app's config.json.

HYPRLAND_CONF="$HOME/.config/hypr/hyprland.conf"
YTMUSIC_DIR="$HOME/.config/YouTube Music Desktop App"
YTMUSIC_CONFIG="$YTMUSIC_DIR/config.json"
YTMUSIC_CSS="$YTMUSIC_DIR/custom-theme.css"

# Get current theme file from Hyprland config
THEME_FILE=$(grep "^source.*themes.*\.conf" "$HYPRLAND_CONF" | sed 's/.*= *//')

if [ -z "$THEME_FILE" ] || [ ! -f "$THEME_FILE" ]; then
    echo "Error: Could not determine theme file from Hyprland config"
    exit 1
fi

if [ ! -f "$YTMUSIC_CONFIG" ]; then
    echo "Error: YouTube Music config not found at $YTMUSIC_CONFIG"
    exit 1
fi

theme_name=$(basename "$THEME_FILE" .conf)

# Extract a color variable from the theme file
get_color() {
    grep "^\$${1} = rgb(" "$THEME_FILE" | sed -E 's/.*= *rgb\(([^)]+)\).*/\1/' | head -1
}

bg_base=$(get_color 'bg-base')
bg_mantle=$(get_color 'bg-mantle')
bg_crust=$(get_color 'bg-crust')
fg_primary=$(get_color 'fg-primary')
fg_secondary=$(get_color 'fg-secondary')
fg_tertiary=$(get_color 'fg-tertiary')
accent_blue=$(get_color 'accent-blue')
accent_green=$(get_color 'accent-green')
accent_red=$(get_color 'accent-red')
accent_yellow=$(get_color 'accent-yellow')
accent_purple=$(get_color 'accent-purple')
accent_cyan=$(get_color 'accent-cyan')
surface_0=$(get_color 'surface-0')
surface_1=$(get_color 'surface-1')
border_0=$(get_color 'border-0')

echo "Syncing YouTube Music theme for: $theme_name"

# Write the custom CSS file
cat > "$YTMUSIC_CSS" << EOF
/* YouTube Music Desktop App — custom theme: $theme_name */
/* Auto-generated by sync-ytmusic-theme.sh — do not edit by hand */

/* ── CSS custom property overrides ──────────────────────────────────────── */
:root,
ytmusic-app,
ytmusic-app-layout {
    /* Backgrounds */
    --yt-spec-base-background:                     #$bg_base !important;
    --yt-spec-raised-background:                   #$surface_0 !important;
    --yt-spec-menu-background:                     #$surface_1 !important;
    --yt-spec-general-background-a:                #$bg_mantle !important;
    --yt-spec-general-background-b:                #$surface_0 !important;
    --yt-spec-general-background-c:                #$bg_base !important;
    /* NOTE: additive-background and static-overlay-background-* are overlay
       layers painted ON TOP of thumbnails/album art — do not override them
       with solid or semi-opaque colors or covers will disappear. */

    /* Text */
    --yt-spec-text-primary:                        #$fg_primary !important;
    --yt-spec-text-secondary:                      #$fg_secondary !important;
    --yt-spec-text-disabled:                       #$border_0 !important;
    --yt-spec-text-primary-inverse:                #$bg_base !important;

    /* Icons */
    --yt-spec-icon-active-other:                   #$fg_primary !important;
    --yt-spec-icon-inactive:                       #$fg_secondary !important;
    --yt-spec-icon-disabled:                       #$border_0 !important;

    /* Brand / accent */
    --yt-spec-brand-icon:                          #$accent_blue !important;
    --yt-spec-brand-link-text:                     #$accent_blue !important;
    --yt-spec-brand-button-background:             #$accent_blue !important;
    --yt-spec-static-brand-red:                    #$accent_red !important;
    --yt-spec-focused-tabitem-indicator:           #$accent_blue !important;
    --yt-spec-selected-nav-text:                   #$accent_blue !important;
    --yt-spec-focus-ring-color:                    #$accent_blue !important;
    --yt-spec-call-to-action:                      #$accent_blue !important;
    --yt-spec-touch-response-inverse:              #${accent_blue}33 !important;

    /* Paper / Polymer component overrides */
    --paper-item-selected-weight:                  600;
    --iron-icon-fill-color:                        #$fg_primary;
}

/* ── Page shell ─────────────────────────────────────────────────────────── */
body,
ytmusic-app {
    background-color: #$bg_base !important;
    color: #$fg_primary !important;
}

/* ── Thumbnail / album-art protection ──────────────────────────────────── */
/* Polymer's shady DOM lets this stylesheet reach inside components.        */
/* Explicitly keep every image container transparent so artwork shows.      */
yt-img-shadow,
yt-img-shadow img,
yt-img-shadow iron-image,
ytmusic-thumbnail-renderer,
ytmusic-thumbnail-renderer img,
ytmusic-player-bar-thumbnail,
ytmusic-player-bar-thumbnail img,
.image-wrapper,
.thumbnail-wrapper {
    background-color: transparent !important;
    background-image: unset;         /* let the element set its own bg-image */
}

/* ── Navigation sidebar ─────────────────────────────────────────────────── */
ytmusic-nav-bar,
ytmusic-side-panel #guide-renderer,
ytmusic-guide-renderer {
    background-color: #$bg_mantle !important;
    border-right: 1px solid #${border_0}40 !important;
}

ytmusic-guide-entry-renderer {
    color: #$fg_secondary !important;
}

ytmusic-guide-entry-renderer:hover {
    background-color: #${surface_0}80 !important;
    color: #$fg_primary !important;
}

ytmusic-guide-entry-renderer[is-selected],
ytmusic-guide-entry-renderer[active] {
    background-color: #${accent_blue}1a !important;
    color: #$accent_blue !important;
}

/* ── Player bar ─────────────────────────────────────────────────────────── */
ytmusic-player-bar {
    background-color: #$bg_mantle !important;
    border-top: 1px solid #${border_0}40 !important;
}

/* Progress bar */
ytmusic-player-bar #progress-bar,
ytmusic-player-bar tp-yt-paper-slider #sliderContainer #slider {
    --paper-slider-active-color:          #$accent_blue !important;
    --paper-slider-knob-color:            #$accent_blue !important;
    --paper-slider-secondary-color:       #${accent_blue}50 !important;
    --paper-slider-container-color:       #$surface_0 !important;
}

/* Volume slider */
ytmusic-player-bar #volume-slider tp-yt-paper-slider #sliderContainer #slider {
    --paper-slider-active-color:          #$accent_blue !important;
    --paper-slider-knob-color:            #$accent_blue !important;
    --paper-slider-container-color:       #$surface_0 !important;
}

ytmusic-player-bar .title {
    color: #$fg_primary !important;
}

ytmusic-player-bar .byline a {
    color: #$fg_secondary !important;
}

/* ── Header / app bar ───────────────────────────────────────────────────── */
/* ytmusic-immersive-header-renderer hosts the hero / blurred album art —   */
/* do NOT set background-color on it or the art disappears.                 */
ytmusic-header-renderer {
    background-color: #${bg_base}e6 !important;
}

/* Search box */
ytmusic-search-box,
ytmusic-search-box input {
    background-color: #$surface_0 !important;
    color: #$fg_primary !important;
    border-color: #${border_0}60 !important;
}

ytmusic-search-box:focus-within {
    border-color: #$accent_blue !important;
}

/* ── Shelf & card surfaces ──────────────────────────────────────────────── */
ytmusic-shelf-renderer,
ytmusic-carousel-shelf-renderer {
    background-color: transparent !important;
}

ytmusic-two-row-item-renderer,
ytmusic-responsive-list-item-renderer {
    --ytmusic-item-hover-bg: #${surface_0}80 !important;
}

ytmusic-two-row-item-renderer:hover,
ytmusic-responsive-list-item-renderer:hover {
    background-color: #${surface_0}80 !important;
}

/* ── Playlist / queue panel ─────────────────────────────────────────────── */
ytmusic-tab-renderer,
ytmusic-queue-container {
    background-color: #$bg_mantle !important;
}

/* Currently playing item highlight */
ytmusic-player-queue-item[selected] {
    background-color: #${accent_blue}1a !important;
}

/* ── Buttons ────────────────────────────────────────────────────────────── */
ytmusic-like-button-renderer tp-yt-paper-icon-button.active,
ytmusic-like-button-renderer iron-icon.active {
    color: #$accent_blue !important;
    fill: #$accent_blue !important;
}

/* ── Menus / dropdowns ──────────────────────────────────────────────────── */
tp-yt-paper-listbox,
tp-yt-paper-dialog,
ytmusic-menu-popup-renderer {
    background-color: #$surface_1 !important;
    color: #$fg_primary !important;
}

tp-yt-paper-item:hover,
ytmusic-menu-navigation-item-renderer:hover {
    background-color: #${accent_blue}1a !important;
}

/* ── Scrollbar ──────────────────────────────────────────────────────────── */
::-webkit-scrollbar {
    width: 6px;
    height: 6px;
}

::-webkit-scrollbar-track {
    background: #$bg_base;
}

::-webkit-scrollbar-thumb {
    background: #$border_0;
    border-radius: 3px;
}

::-webkit-scrollbar-thumb:hover {
    background: #$accent_blue;
}
EOF

# Enable custom CSS in config.json using python3
python3 - << PYEOF
import json, sys

config_file = "$YTMUSIC_CONFIG"
css_path    = "$YTMUSIC_CSS"

try:
    with open(config_file, 'r') as f:
        config = json.load(f)
except Exception as e:
    print(f"Error reading config: {e}", file=sys.stderr)
    sys.exit(1)

config.setdefault('appearance', {})
config['appearance']['customCSSEnabled'] = True
config['appearance']['customCSSPath']    = css_path

try:
    with open(config_file, 'w') as f:
        json.dump(config, f, indent='\t')
    print("config.json updated: customCSSEnabled=true")
except Exception as e:
    print(f"Error writing config: {e}", file=sys.stderr)
    sys.exit(1)
PYEOF

echo "YouTube Music theme synced successfully ($theme_name → $YTMUSIC_CSS)"
echo "Restart YouTube Music Desktop App to apply the new theme."
