#!/bin/bash

# Sync k9s skin with current Hyprland theme.
# Writes a skin YAML to ~/.config/k9s/skins/<theme>.yaml and updates
# (or creates) ~/.config/k9s/config.yaml to reference it.

HYPRLAND_CONF="$HOME/.config/hypr/hyprland.conf"
K9S_DIR="$HOME/.config/k9s"
K9S_SKINS_DIR="$K9S_DIR/skins"
K9S_CONFIG="$K9S_DIR/config.yaml"

# Get current theme file from Hyprland config
THEME_FILE=$(grep "^source.*themes.*\.conf" "$HYPRLAND_CONF" | sed 's/.*= *//')

if [ -z "$THEME_FILE" ] || [ ! -f "$THEME_FILE" ]; then
    echo "Error: Could not determine theme file from Hyprland config"
    exit 1
fi

theme_name=$(basename "$THEME_FILE" .conf)
skin_name="${theme_name,,}"   # lowercase, e.g. "gruvbox"
skin_file="$K9S_SKINS_DIR/${skin_name}.yaml"

# Extract a color variable from the theme file
get_color() {
    grep "^\$${1} = rgb(" "$THEME_FILE" | sed -E 's/.*= *rgb\(([^)]+)\).*/\1/' | head -1
}

bg_base=$(get_color 'bg-base')
bg_mantle=$(get_color 'bg-mantle')
fg_primary=$(get_color 'fg-primary')
fg_secondary=$(get_color 'fg-secondary')
fg_tertiary=$(get_color 'fg-tertiary')
accent_blue=$(get_color 'accent-blue')
accent_green=$(get_color 'accent-green')
accent_yellow=$(get_color 'accent-yellow')
accent_red=$(get_color 'accent-red')
accent_orange=$(get_color 'accent-orange')
accent_purple=$(get_color 'accent-purple')
accent_cyan=$(get_color 'accent-cyan')
surface_0=$(get_color 'surface-0')
surface_1=$(get_color 'surface-1')
surface_2=$(get_color 'surface-2')
border_0=$(get_color 'border-0')
border_1=$(get_color 'border-1')

echo "Syncing k9s skin for: $theme_name"

mkdir -p "$K9S_SKINS_DIR"

cat > "$skin_file" << EOF
# k9s skin: $theme_name
# Auto-generated by sync-k9s-theme.sh — do not edit by hand
k9s:
  body:
    fgColor: "#$fg_primary"
    bgColor: "#$bg_base"
    logoColor: "#$accent_green"
  prompt:
    fgColor: "#$fg_primary"
    bgColor: "#$surface_0"
    suggestColor: "#$accent_blue"
  info:
    fgColor: "#$accent_blue"
    sectionColor: "#$fg_primary"
  dialog:
    fgColor: "#$fg_primary"
    bgColor: "#$surface_1"
    buttonFgColor: "#$bg_base"
    buttonBgColor: "#$accent_blue"
    buttonFocusFgColor: "#$bg_base"
    buttonFocusBgColor: "#$accent_yellow"
    labelFgColor: "#$accent_orange"
    fieldFgColor: "#$fg_primary"
  frame:
    border:
      fgColor: "#$border_0"
      focusColor: "#$accent_blue"
    menu:
      fgColor: "#$fg_primary"
      keyColor: "#$accent_blue"
      numKeyColor: "#$accent_yellow"
    crumbs:
      fgColor: "#$bg_base"
      bgColor: "#$accent_blue"
      activeColor: "#$accent_yellow"
    status:
      newColor: "#$accent_green"
      modifyColor: "#$accent_blue"
      addColor: "#$accent_green"
      errorColor: "#$accent_red"
      highlightColor: "#$accent_yellow"
      killColor: "#$accent_red"
      completedColor: "#$fg_tertiary"
    title:
      fgColor: "#$fg_primary"
      bgColor: "#$bg_base"
      highlightColor: "#$accent_yellow"
      counterColor: "#$accent_blue"
      filterColor: "#$accent_green"
  views:
    charts:
      bgColor: default
      defaultDialColors:
        - "#$accent_blue"
        - "#$accent_red"
      defaultChartColors:
        - "#$accent_blue"
        - "#$accent_green"
    table:
      fgColor: "#$fg_primary"
      bgColor: "#$bg_base"
      header:
        fgColor: "#$accent_yellow"
        bgColor: "#$bg_base"
        sorterColor: "#$accent_green"
    xray:
      fgColor: "#$fg_primary"
      bgColor: "#$bg_base"
      cursorColor: "#$surface_0"
      graphicColor: "#$accent_blue"
      showIcons: false
    yaml:
      keyColor: "#$accent_red"
      colonColor: "#$fg_tertiary"
      valueColor: "#$accent_green"
    logs:
      fgColor: "#$fg_primary"
      bgColor: "#$bg_base"
      indicator:
        fgColor: "#$fg_primary"
        bgColor: "#$accent_blue"
EOF

# Update (or create) config.yaml to reference this skin.
# Only touches the skin line; leaves everything else untouched.
update_k9s_config() {
    if [ ! -f "$K9S_CONFIG" ]; then
        cat > "$K9S_CONFIG" << CFGEOF
k9s:
  ui:
    skin: $skin_name
CFGEOF
        echo "Created $K9S_CONFIG with skin: $skin_name"
        return
    fi

    if grep -q '^\s*skin:' "$K9S_CONFIG"; then
        sed -i "s|^\(\s*\)skin:.*|\1skin: $skin_name|" "$K9S_CONFIG"
    elif grep -q '^\s*ui:' "$K9S_CONFIG"; then
        sed -i "/^\s*ui:/a\\    skin: $skin_name" "$K9S_CONFIG"
    elif grep -q '^k9s:' "$K9S_CONFIG"; then
        sed -i "/^k9s:/a\\  ui:\n    skin: $skin_name" "$K9S_CONFIG"
    else
        printf '\nk9s:\n  ui:\n    skin: %s\n' "$skin_name" >> "$K9S_CONFIG"
    fi

    echo "Updated $K9S_CONFIG: skin = $skin_name"
}

update_k9s_config

echo "k9s skin synced successfully ($theme_name → $skin_file)"
